name: online_panchayat_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.95+109

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amazon_cognito_identity_dart_2: ^3.2.0
  amplify_auth_cognito: ^0.5.1
  amplify_storage_s3: ^0.5.1
  amplify_flutter: ^0.5.1
  firebase_core: ^1.1.0
  firebase_messaging: ^13.1.0
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
 
  firebase_in_app_messaging: ^0.6.0+27
  velocity_x: ^3.1.0
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  provider: ^6.0.5
  image_picker: ^0.8.4+6
  image_cropper: ^3.0.1
  location: ^4.3.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.0.3

  day_night_switcher: ^0.2.0+1
  share: ^2.0.1
  address_finder:
    path: address_finder
  youtube_parser: ^2.0.0
  connectivity: ^3.0.3
  sms_autofill: ^2.0.0
  flutter_inappwebview: ^5.3.2
  firebase_crashlytics: ^2.0.3
  firebase_remote_config: ^2.0.20
  package_info: ^2.0.0
 
  better_player: ^0.0.68
  youtube_explode_dart: ^1.10.6
  url_launcher: ^6.0.6
  metadata_fetch: ^0.4.1
  photo_view: ^0.14.0
  youtube_player_iframe: ^4.0.4
  visibility_detector: ^0.3.3
  flutter_local_notifications:
    path: flutter_local_notifications/flutter_local_notifications
  geoflutterfire: ^3.0.1
  auto_size_text:
  wakelock: ^0.6.2
  percent_indicator: ^4.2.3
  flutter_spinkit: ^5.1.0
  video_compress: ^3.1.0

  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.4.0
  feature_discovery: ^0.14.0
  flutter_share_me: ^1.2.0
  in_app_update: ^4.0.1
  # flutter_native_admob: 
  #   path: flutter_native_admob
  uni_links: ^0.5.1
  carousel_slider: ^4.0.0
  flutter_geo_hash: ^0.0.4
  auto_animated: ^3.0.1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  platform : ^3.1.0
  razorpay_flutter: ^1.3.0
  screenshot: ^1.2.3
  share_plus: ^6.3.1
  path_provider: ^2.0.10
  snackbar: ^1.0.2
  firebase_analytics: ^9.3.8
  youtube_player_flutter: ^8.1.2
  firebase_dynamic_links: ^4.3.11
  geocoder2: ^1.4.0
 

dev_dependencies:
  # build_runner: ^1.0.0      #for json serialization
  # json_serializable: ^3.3.0 #for json serialization
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons:

dependency_overrides:
  crypto: ^3.0.0
  # htt
  http: ^0.13.0
  http_parser: ^4.0.0
  xml: ^5.0.0
  args: ^2.0.0
  meta: ^1.4.0
  plugin_platform_interface: ^2.0.0
  firebase_core_platform_interface: 4.5.1
  # http: ^0.12.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/otp_icon.webp
    - assets/countrycodes.json
    - assets/images/
    # - assets/serviceImages/
    - assets/icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  # color_dark: "#000000"
  # image_dark: assets/splash.png
  fullscreen: true
  # android_gravity: display_clip_horizontal
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
# flutter pub run flutter_native_splash:create
